In [24]:
import torch

a = torch.arange(10, 150, step=10)
a

tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130, 140])

In [25]:
b = torch.triu(torch.arange(9).view(-1, 3))
b

tensor([[0, 1, 2],
        [0, 4, 5],
        [0, 0, 8]])

In [26]:
a[b]

tensor([[10, 20, 30],
        [10, 50, 60],
        [10, 10, 90]])

In [27]:
ind = b % 2 == 0
ind

tensor([[ True, False,  True],
        [ True,  True, False],
        [ True,  True,  True]])

In [28]:
b[ind]

tensor([0, 2, 0, 4, 0, 0, 8])

In [29]:
a = torch.arange(9).view(-1 , 3)
a.sum()

tensor(36)

In [32]:
a.sum(axis=1)

tensor([ 3, 12, 21])

In [33]:
a

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [34]:
a / a.sum(axis=1)

tensor([[0.0000, 0.0833, 0.0952],
        [1.0000, 0.3333, 0.2381],
        [2.0000, 0.5833, 0.3810]])

In [36]:
a / a.sum(axis=1,keepdim=True)

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167],
        [0.2857, 0.3333, 0.3810]])