In [1]:
import torch

/home/oren/projects/passing_the_torch/venv/lib/python3.10/site-packages/torch/_subclasses/functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [2]:
person_details = torch.tensor([18.0, 172.4]) # first entry age in years, second entry hight in centimeters 

In [3]:
person_details

tensor([ 18.0000, 172.4000])

In [4]:
subjects_details = torch.tensor([
    [18.0, 172.4],
    [51.0, 169.2],
    [46.0, 164.5],
])

subjects_details

tensor([[ 18.0000, 172.4000],
        [ 51.0000, 169.2000],
        [ 46.0000, 164.5000]])

In [13]:
# first entry age in years, second entry height in centimeters, and just added the mass in kilograms.
subjects_details = torch.tensor([
    [18.0, 172.4, 62.1],
    [51.0, 169.2, 66.0],
    [46.0, 164.5, 72.0],
])

subjects_BMI = (
    subjects_details[:, 2] / (subjects_details[:, 1] / 100.0) ** 2
)

subjects_BMI

tensor([20.8938, 23.0538, 26.6073])

In [12]:
62.1 / (172.4 / 100.0) ** 2

20.893782871539237