In [1]:
import torch

In [2]:
person_details = torch.tensor([18, 172.4]) # first entry age in years, second entry hight in centimeters 

In [3]:
person_details

tensor([ 18.0000, 172.4000])

In [4]:
subjects_details = torch.tensor([
    [18.0, 172.4],
    [51.0, 169.2],
    [46.0, 164.5],
])

subjects_details

tensor([[ 18.0000, 172.4000],
        [ 51.0000, 169.2000],
        [ 46.0000, 164.5000]])

In [5]:
# first entry age in years, second entry height in centimeters, and just added the mass in kilograms.
subjects_details = torch.tensor([
    [18.0, 172.4, 62.1],
    [51.0, 169.2, 66.0],
    [46.0, 164.5, 72.0],
])

subjects_BMI = (
    subjects_details[:, 2] / (subjects_details[:, 1] / 100.0) ** 2
)

subjects_BMI

tensor([20.8938, 23.0538, 26.6073])

In [6]:
62.1 / (172.4 / 100.0) ** 2

20.893782871539237

In [7]:
subjects_details = torch.tensor([
    [18, 172.4],
    [51, 169.2],
    [46, 164.5],
])

subjects_details

tensor([[ 18.0000, 172.4000],
        [ 51.0000, 169.2000],
        [ 46.0000, 164.5000]])

In [8]:
type(subjects_details)

torch.Tensor

In [9]:
subjects_details.type()

'torch.FloatTensor'

In [10]:
subjects_details.dtype

torch.float32

In [11]:
subjects_details.shape

torch.Size([3, 2])

In [12]:
img = torch.tensor([
    [0, 1, 1, 0],
    [1, 0, 0, 1],
    [1, 0, 0, 1],
    [0, 1, 1, 0],
])

img

tensor([[0, 1, 1, 0],
        [1, 0, 0, 1],
        [1, 0, 0, 1],
        [0, 1, 1, 0]])

In [13]:
img.type()

'torch.LongTensor'

In [14]:
img = torch.Tensor([
    [0, 1, 1, 0],
    [1, 0, 0, 1],
    [1, 0, 0, 1],
    [0, 1, 1, 0],
])

img

tensor([[0., 1., 1., 0.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [0., 1., 1., 0.]])

In [15]:
img = torch.tensor([
    [0, 1, 1, 0],
    [1, 0, 0, 1],
    [1, 0, 0, 1],
    [0, 1, 1, 0],
])

img.to(torch.float32)

tensor([[0., 1., 1., 0.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [0., 1., 1., 0.]])

In [16]:
chw_img = img.unsqueeze(0).repeat(3, 1, 1)
chw_img

tensor([[[0, 1, 1, 0],
         [1, 0, 0, 1],
         [1, 0, 0, 1],
         [0, 1, 1, 0]],

        [[0, 1, 1, 0],
         [1, 0, 0, 1],
         [1, 0, 0, 1],
         [0, 1, 1, 0]],

        [[0, 1, 1, 0],
         [1, 0, 0, 1],
         [1, 0, 0, 1],
         [0, 1, 1, 0]]])

In [17]:
chw_img[1] *= 2
chw_img[2] *= 3
chw_img

tensor([[[0, 1, 1, 0],
         [1, 0, 0, 1],
         [1, 0, 0, 1],
         [0, 1, 1, 0]],

        [[0, 2, 2, 0],
         [2, 0, 0, 2],
         [2, 0, 0, 2],
         [0, 2, 2, 0]],

        [[0, 3, 3, 0],
         [3, 0, 0, 3],
         [3, 0, 0, 3],
         [0, 3, 3, 0]]])

In [18]:
chw_img.permute(1, 2, 0)[:, :, 2]

tensor([[0, 3, 3, 0],
        [3, 0, 0, 3],
        [3, 0, 0, 3],
        [0, 3, 3, 0]])

In [19]:
chw_img.shape

torch.Size([3, 4, 4])

In [20]:
hwc_img = chw_img.permute(1, 2, 0)
hwc_img.permute(2, 0, 1)

tensor([[[0, 1, 1, 0],
         [1, 0, 0, 1],
         [1, 0, 0, 1],
         [0, 1, 1, 0]],

        [[0, 2, 2, 0],
         [2, 0, 0, 2],
         [2, 0, 0, 2],
         [0, 2, 2, 0]],

        [[0, 3, 3, 0],
         [3, 0, 0, 3],
         [3, 0, 0, 3],
         [0, 3, 3, 0]]])

In [21]:
img_vec = torch.arange(9)
print(img_vec.shape)
img_mat = img_vec.reshape(-1, 3)
print(img_mat.shape)

torch.Size([9])
torch.Size([3, 3])


In [22]:
img_mat

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [23]:
img_mat[-1, -1] = 88
img_vec

tensor([ 0,  1,  2,  3,  4,  5,  6,  7, 88])

In [24]:
tensor1 = torch.randn(3)
tensor2 = torch.randn(3)
res = torch.matmul(tensor1, tensor2)
print(res)
print(res.size())
print(res.item())

tensor(-1.3644)
torch.Size([])
-1.364400863647461


In [25]:
torch.cuda.is_available()

False

In [26]:
img = torch.tensor([
    [0, 1, 1, 0],
    [1, 0, 0, 1],
    [1, 0, 0, 1],
    [0, 1, 1, 0],
])

img * torch.tensor([[[1]], [[2]], [[3]]])

tensor([[[0, 1, 1, 0],
         [1, 0, 0, 1],
         [1, 0, 0, 1],
         [0, 1, 1, 0]],

        [[0, 2, 2, 0],
         [2, 0, 0, 2],
         [2, 0, 0, 2],
         [0, 2, 2, 0]],

        [[0, 3, 3, 0],
         [3, 0, 0, 3],
         [3, 0, 0, 3],
         [0, 3, 3, 0]]])

In [35]:
t1 = torch.tensor([1.1, 2, 3, 4, 5])

t1[t1 != 2]

tensor([1.1000, 3.0000, 4.0000, 5.0000])

In [36]:
(t1 != 2).type()

'torch.BoolTensor'

In [37]:
(t1 != 2).shape

torch.Size([5])

In [43]:
t1[torch.tensor([0, 0, 0, 1, 1, 1, 1, 3])]

tensor([1.1000, 1.1000, 1.1000, 2.0000, 2.0000, 2.0000, 2.0000, 4.0000])

In [47]:
t2 = torch.tensor([[1.1, 2, 3, 4, 5], [2, 2, 3, 4, 5]])

In [48]:
t2[t2 != 2]

tensor([1.1000, 3.0000, 4.0000, 5.0000, 3.0000, 4.0000, 5.0000])